---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: app-secrets
spec:
  provider: gcp
  secretObjects:
  - secretName: apisecret
    type: Opaque
    data:
    # https://secrets-store-csi-driver.sigs.k8s.io/topics/sync-as-kubernetes-secret.html
    # https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/issues/37
    - objectName: secret.txt
      key: pwd
  parameters:
    secrets: |
      - resourceName: "{{ .Values.gcp_secert_location }}"
        fileName: secret.txt
