---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Values.ServiceAccountName }}"
  namespace: "{{ .Values.namespace }}"
  annotations:
    iam.gke.io/gcp-service-account: "{{ .Values.gcp_service_account }}"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "weather"
  namespace: "{{ .Values.namespace }}" 
  labels:
    app: "weather"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "weather"
  template:
    metadata:
      labels:
        app: "weather"
    spec:
      serviceAccountName: "{{ .Values.ServiceAccountName }}"
      containers:
      - name: "weather-cont"
        env:
        # https://secrets-store-csi-driver.sigs.k8s.io/topics/set-as-env-var.html
        - name: APIKEY
          valueFrom:
            secretKeyRef:
              name: apisecret
              key: pwd
        image: "{{ .Values.image }}"
        ports:
          # https://cloud.google.com/kubernetes-engine/docs/concepts/ingress#health_checks
          - containerPort: {{ .Values.container_port }}
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /health
            port: {{ .Values.container_port }}
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /health
            port: {{ .Values.container_port }}
          initialDelaySeconds: 10
          periodSeconds: 5
        volumeMounts:
          - mountPath: "/var/secrets"
            name: weathersecret
      volumes:
      - name: weathersecret
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "app-secrets"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "weather"
  namespace: "{{ .Values.namespace }}"
  labels:
    app: "weather"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "weather"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
